# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    queue_host: '%env(QUEUE_HOST)%'
    queue_port: '%env(QUEUE_PORT)%'
    queue_user: '%env(QUEUE_USER)%'
    queue_password: '%env(QUEUE_PASSWORD)%'

    app.jwt_secret_key: '%env(JWT_SECRET_KEY)%'
    app.jwt_token_ttl: '%env(int:JWT_TOKEN_TTL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
#        exclude:
#            - '../src/EventListeners/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Event Listeners
    App\EventListeners\BatchQueueEventListener:
        tags:
            - { name: kernel.event_listener, event: 'batch.user.notification', method: process }

    # Services
    App\Service\Queue\BatchQueueService:
        arguments:
            $host: '%queue_host%'
            $port: '%queue_port%'
            $user: '%queue_user%'
            $password: '%queue_password%'

imports:
    - { resource: services/security.yaml }
